### ISSUE TITLE
sideloading not working for comments

### ISSUE THREAD

**Issue by mikeboulet-haw** [zendesk/zendesk_api_client_php#16]
$client->tickets()->comments()->sideload(['users'])->findAll($params) is returning the comments but not the sideloaded users.

**Comment by buheryfi** [comment]
@mikeboulet-haw are you still having issues with side-loading users with the Tickets Class?  If so, can you create share a gist of the code you're using?

**Comment by atroche** [comment]
will close this unless @mikeboulet-haw is still having issues
