### ISSUE TITLE
Possible XSS and Information disclosure in Http::send

### ISSUE THREAD

**Issue by uuid0** [zendesk/zendesk_api_client_php#163]
In the current dev-master the debug info is automatically printed if the response was >= 400.
The debug info may contain the authorization header, among other things.

Since the LastRequestHeaders is reflected, it is also possible to inject JS code if for instance the id wasn't validated properly in a search request.

        [...]
        if ($responseCode >= 400) {
            print($client->getDebug());
            throw new ResponseException(__METHOD__);
        }
        [...]

https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Http.php#L149

v1.2.0 appears to be okay.
I did not check other parts of the code or other versions, though. I currently don't have the time. I just wanted to pass this information quickly.

**Comment by jwswj** [comment]
@uuid0 a fair chunk of this API client has been rewritten and we're now using [Guzzle to make requests](https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Http.php#L114-L116) and any error will throw a `Zendesk\API\Exceptions\ApiResponseException` (https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Exceptions/ApiResponseException.php) which is basically a `GuzzleHttp\Exception\RequestException`
