### ISSUE TITLE
Fatal error: Class 'Zendesk\API\Client' not found

### ISSUE THREAD

**Issue by webmastersean365** [zendesk/zendesk_api_client_php#168]
I've installed via Composer and in my php page (in the same directory as the vendor directory) I have copied this and put in my settings:

use Zendesk\API\Client as ZendeskAPI;

$subdomain = "subdomain";
$username  = "username";
$token     = "6wiIBWbGkBMo1mRDMuVwkw1EPsNkeUj95PIz2akv"; // replace this with your token
// $password = "123456";

$client = new ZendeskAPI($subdomain, $username);
$client->setAuth('token', $token); // set either token or password

My page is giving the error: Fatal error: Class 'Zendesk\API\Client' not found

For more context, I'm trying to use the library as a plugin to my CMS system, but that shouldn't matter...  

I'm using PHP Version 5.5.24...

Are there any troubleshooting steps I could take to help solve this?

Thanks!

Sean

**Comment by buheryfi** [comment]
Hi Sean,

Just curious, if you put the PHP page in the directory above vendor does it work for you?  I've always been using it by putting my PHP page in the root directory of this library and not had issues.

Otherwise, could you provide a gist of your PHP page (removing any sensitive information) and perhaps a stack trace of the error?

Sincerely,
James Peterson

**Comment by rearley** [comment]
At any point is the composer's autoload being required in the script that the above code is being called?

require_once(".vendor/autoload.php");

**Comment by 0rgan1c** [comment]
I am having the same exact issue. The error message I get is:
`Fatal error: Class 'Zendesk\API\Client' not found in X:\xampp\htdocs\zendesk2\api.php on line 12`

Here is the corresponding code:
```
<?php
// load Composer
require 'vendor/autoload.php';

use Zendesk\API\Client as ZendeskAPI;

$subdomain = "xxxxxxxxxx";
$username  = "xxxxxxxxxx";
$token     = "xxxxxxxxxx"; // replace this with your token
// $password = "123456";

$client = new ZendeskAPI($subdomain, $username);
$client->setAuth('token', $token); // set either token or password

// Get all tickets
$tickets = $client->tickets()->findAll();
print_r($tickets);
?>
```

Folder Structure:
* zendesk2/ (root)
  * vendor
  * api.php

Here are the resources I used. Everything I did was essentially an exact copy/paste:
* [A short & simple Composer tutorial](http://www.dev-metal.com/composer-tutorial/)
* [Zendesk PHP API Client Library (README.md)](https://github.com/zendesk/zendesk_api_client_php)

**Comment by rearley** [comment]
First, try;

``` composer dump-autoload```

See if that helps. I tried the code as you showed in your example and I was able to run it without issue. What is in your composer.json file? I have the following:

```"zendesk/zendesk_api_client_php": "dev-master"```

Also have you updated the library or did you just recently download it?

**Comment by 0rgan1c** [comment]
Hi rearley, thanks for the reply.

I tried what you suggested, and it gives the same results.
```
X:\xampp\htdocs\zendesk2>composer dump-autoload
Generating autoload files
```

Here is my composer.json

```
{
  "require": {
    "zendesk/zendesk_api_client_php": "dev-master"
  }
}
```

I have not updated the library, and I just downloaded it yesterday (first time using composer, so I'm unaware/uncertain how to do this). Based off these links I ran the following command, but I don't know if I did it correctly or what you were asking me to do:
* [Composer Basic usage](https://getcomposer.org/doc/03-cli.md#update)
* [php composer.phar update does not work](http://stackoverflow.com/questions/12355540/php-composer-phar-update-does-not-work)

```
X:\xampp\htdocs\zendesk2>php C:\ProgramData\ComposerSetup\bin\composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating zendesk/zendesk_api_client_php dev-master (e4b73c6 => dac153f)
    Checking out dac153ff0e5e4693286d07270a431a0e44e61f48

Writing lock file
Generating autoload files
```

Sadly I still get the message `Fatal error: Class 'Zendesk\API\Client' not found in X:\xampp\htdocs\zendesk2\api.php on line 12` :(

**Comment by rearley** [comment]
If you look inside you're  vendor directory, do you see the zendesk files? I am at a loss because I used the code you had above without issue. Something does not appear to be auto loading properly.

**Comment by 0rgan1c** [comment]
Here is what I know/observed:

* I do see files in the vendor folder (tree below)
* the vendor/autoload.php appears it's being included, because if I rename/move that file, it gives the error:
```
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in X:\xampp\htdocs\zendesk2\api.php on line 3

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.;X:\xampp\php\PEAR') in X:\xampp\htdocs\zendesk2\api.php on line 3
```
* If I change `use Zendesk\API\Client as ZendeskAPI;` to `use Zendesk\API\HttpClient as ZendeskAPI;` (I don't know what this is, but noticed it is used here [zendesk_api_client_php/index.php](https://github.com/zendesk/zendesk_api_client_php/blob/master/index.php)) it gives a different error:

```
Catchable fatal error: Argument 2 passed to Zendesk\API\HttpClient::setAuth() must be of the type array, string given, called in X:\xampp\htdocs\zendesk2\api.php on line 13 and defined in
X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\HttpClient.php on line 259
```

* I tried to upload it to my webhost (instead of using xampp) by FTP'ing the whole folder (not sure if I need to do anything special), and essentially get the same error:
```
Fatal error: Class 'Zendesk\API\Client' not found in /home/organic/public_html/zendesk2/api.php on line 12
```

I'm not sure if any of this information is helpful.

```
X:\xampp\htdocs\zendesk2>tree
Folder PATH listing
Volume serial number is 6854-65D8
X:.
└───vendor
    ├───composer
    ├───guzzlehttp
    │   ├───guzzle
    │   │   ├───build
    │   │   ├───docs
    │   │   ├───src
    │   │   │   ├───Cookie
    │   │   │   ├───Exception
    │   │   │   └───Handler
    │   │   └───tests
    │   ├───promises
    │   │   ├───src
    │   │   └───tests
    │   └───psr7
    │       ├───src
    │       └───tests
    ├───mmucklo
    │   └───inflect
    │       ├───src
    │       │   └───Inflect
    │       └───tests
    ├───psr
    │   └───http-message
    │       └───src
    └───zendesk
        └───zendesk_api_client_php
            ├───src
            │   └───Zendesk
            │       └───API
            │           ├───Exceptions
            │           ├───Resources
            │           │   ├───Core
            │           │   ├───HelpCenter
            │           │   └───Voice
            │           ├───Traits
            │           │   ├───Resource
            │           │   └───Utility
            │           └───Utilities
            └───tests
                ├───assets
                └───Zendesk
                    └───API
                        ├───LiveTests
                        ├───MockTests
                        └───UnitTests
                            ├───Core
                            ├───HelpCenter
                            └───Voice
```

**Comment by jwswj** [comment]
We missed a critical change in our documentation when merging in the new version of the API client which is causing these errors. Hopefully https://github.com/zendesk/zendesk_api_client_php/pull/184 resolves the issues you've been running into.

**Comment by 0rgan1c** [comment]
Hi Jason, thank you very much. That explains a lot! I now get a different error message, but happy to see a change in the right direction nonetheless!

This code:
```
$tickets = $client->tickets()->findAll();
print_r($tickets);
```
Results in:
`Fatal error:  Call to a member function getReasonPhrase() on null in X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Exceptions\ApiResponseException.php on line 22`

However, when I change it to this, the error goes away and I get something printed:
```
$tickets = $client->tickets();
print_r($tickets);
```

```
Zendesk\API\Resources\Core\Tickets Object
(
    [lastAttachments:protected] => Array
        (
        )

    [resourceName:protected] => tickets
    [objectName:protected] => ticket
    [objectNamePlural:protected] => tickets
    [client:protected] => Zendesk\API\HttpClient Object 

(next 236 lines removed)
```

**Comment by jwswj** [comment]
@0rgan1c are you able to use any of the other functions? Like creating a new ticket:
```php
$newTicket = $client->tickets()->create(array(
  'subject'  => 'The quick brown fox jumps over the lazy dog',
  'comment'  => array(
    'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
  ),
  'priority' => 'normal'
));
print_r($newTicket);
```

$client->tickets() is just returning the empty Tickets Object. findAll() is what actually makes an API call, gets the tickets and transforms the JSON response into PHP objects.

Are you using the php 5.5+?
Are there any more details printed about the error?

**Comment by 0rgan1c** [comment]
@jwswj Oh yes thank you, I understand that, I was just including that for troubleshooting purposes and wanted to include my observation. 

* XAMPP for Windows 5.5.27 & 5.6.11
* From phpinfo():
  * PHP Version 5.6.11
  * cURL support: enabled
* This morning I created a new folder, new composer.json, and `composer install` from scratch
* Copy/pasted code from readme
* No other details printed about errors, will copy/paste exactly as displayed

**New ticket**
```
Fatal error: Call to a member function getReasonPhrase() on null in X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Exceptions\ApiResponseException.php on line 22
```

**Update ticket**
```
$client->ticket([1377])->update([
    'status' => 'urgent'
]);
```
```
Fatal error: Uncaught exception 'Exception' with message 'No method called ticket available in Zendesk\API\HttpClient' in 
X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Traits\Utility\InstantiatorTrait.php:33 Stack trace: #0 X:\xampp\htdocs\zendesk2\api.php(16): Zendesk\API\HttpClient->__call('ticket', Array) #1 
X:\xampp\htdocs\zendesk2\api.php(16): Zendesk\API\HttpClient->ticket(Array) #2 {main} thrown in X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Traits\Utility\InstantiatorTrait.php on line 33
```
**Deleting  ticket**
```
$client->ticket(1377)->delete();
```
```
Fatal error: Uncaught exception 'Exception' with message 'No method called ticket available in Zendesk\API\HttpClient' in 
X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Traits\Utility\InstantiatorTrait.php:33 Stack trace: #0 X:\xampp\htdocs\zendesk2\api.php(16): Zendesk\API\HttpClient->__call('ticket', Array) #1 
X:\xampp\htdocs\zendesk2\api.php(16): Zendesk\API\HttpClient->ticket(1377) #2 {main} thrown in X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Traits\Utility\InstantiatorTrait.php on line 33
```

**Comment by jwswj** [comment]
@0rgan1c you've found more examples that haven't been updated. Apologies again. The ticket class doesn't exist in v2. Everything is based off the tickets() class. To delete a ticket:
`$client->tickets()->delete(1377)`
Update is causing me some trouble. I'll update this thread with an example when I work it out and get a chance to speak with @miogalang and @joseconsador

**Comment by 0rgan1c** [comment]
@jwswj No problem, I am happy to help. Please let me know if there is anything else I can do or try to get you what you need. Sounds good, I look forward to the update.

In case this is useful, I just wanted to report when I tried `$client->tickets()->delete(1377);` it returned:
```
Fatal error: Call to a member function getReasonPhrase() on null in X:\xampp\htdocs\zendesk2\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Exceptions\ApiResponseException.php on line 22
```

**Comment by suman-khatri** [comment]
Hi, 
    I got same error : ( ! ) Fatal error: Call to a member function getReasonPhrase() on a non-object in C:\wamp\www\zendeskapi\src\Zendesk\API\Exceptions\ApiResponseException.php on line 22.

can anyone help me regarding this...

**Comment by miogalang** [comment]
Hi @suman-khatri. Can you show me the snippet of the code you are trying to run? also may I ask what version on composer are you using of the client?

**Comment by suman-khatri** [comment]
hi @miogalang . Here is the snippet of the code:
<?php
include("../vendor/autoload.php");

use Zendesk\API\HttpClient as ZendeskAPI;

/**
 * Replace the following with your own.
 */
$subdomain = "xxxxxxx";
$username  = "xxxxxxxxxx";
$token     = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

$client = new ZendeskAPI($subdomain, $username);
$client->setAuth('basic', ['username' => $username, 'token' => $token]);

try {
    // Get all tickets
    $tickets = $client->tickets()->findAll();
    // Create a new ticket
    $newTicket = $client->tickets()->create(array(
        'subject'  => 'The quick brown fox jumps over the lazy dog',
        'comment'  => array(
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
        ),
        'priority' => 'normal'
    ));

    print_r($tickets);
    print_r($newTicket);
} catch (\Zendesk\API\Exceptions\ApiResponseException $e) {
    echo 'Please check your credentials. Make sure to change the $subdomain, $username, and $token variables in this file.';
}

**Comment by suman-khatri** [comment]
and i didn't specify version while installing composer.

**Comment by miogalang** [comment]
Hi @suman-khatri Did you install the client via composer?
 Can I take a look at the line for zendesk on your composer.json to figure out what version of the client you are running?

 We have merged recently a fix which will return a better error and give you the error message from the API.

In your code above. May I suggest you looking at the contents of $e to see the error message.

```
} catch (\Zendesk\API\Exceptions\ApiResponseException $e) {
echo 'Please check your credentials. Make sure to change the $subdomain, $username, and $token variables in this file.';
}
```

to 

```
} catch (\Zendesk\API\Exceptions\ApiResponseException $e) {
echo $e->__toString();
echo 'Please check your credentials. Make sure to change the $subdomain, $username, and $token variables in this file.';
}
```

**Comment by suman-khatri** [comment]
@miogalang I have checked and control is not going in the catch block...
It is stucked somewhere in try block....

**Comment by suman-khatri** [comment]
@miogalang I got the following error:
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\wamp\www\zendeskapi\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 169

**Comment by suman-khatri** [comment]
@miogalang I got the following error:
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\wamp\www\zendeskapi\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 169
   
To resolve this I added two files in C:/wamp folder named: 
1. ca-bundle.crt
2. cacert.pem

and added path in php.ini file 
curl.cainfo = "c:/wamp/cacert.pem"
openssl.cafile="C:/wamp/ca-bundle.crt"

still am getting the same error... :(

**Comment by mundoEarth** [comment]
@jwswj  Where can I found the new version of php api client? because I have encountered same issue on "Class 'Zendesk\API\HttpClient' not found". 
@0rgan1c  did you solve that problem with this issue "Class 'Zendesk\API\HttpClient' not found"?

**Comment by jwswj** [comment]
The new version of the API client uses the HttpClient namespace and is found in the master branch of this repo. There is also an [upgrade guide](https://github.com/zendesk/zendesk_api_client_php/wiki/Upgrading-from-v1-to-v2). You're issue sounds different to `getReasonPhrase` and `Class 'Zendesk\API\Client'` issues which are in this issue and are most likely related to an autoload/require issue. Please open another issue if you're having problems.

**Comment by sam452** [comment]
I am getting this error after following the examples above, just trying to get to first base. Unfortunately, in all the responses above, they never seem to address the error? I used composer to install the zendesk_api_client_php. I have several folders in my vendor. My attempt to require vendor/autoload.php appears to not result in any error when using the PHP -a console (my primary way to explore interactively a new library).
composer.json =>
`{
  "name": "zendesk/zendesk_api_client_php",
  "description": "PHP Client for Zendesk REST API. See http://developer.zendesk.com/api-docs",
  "license": "Apache License Version 2.0",
  "homepage": "https://github.com/zendesk/zendesk_api_client_php",
  "require": {
    "php": ">=5.5.0",
    "guzzlehttp/guzzle": "~6.0",
    "mmucklo/inflect": "0.3.*"
  },
  "require-dev": {
    "phpunit/phpunit": "4.5.*",
    "squizlabs/php_codesniffer": "2.*",
    "phpmd/phpmd": "@stable",
    "fzaninotto/faker": ">=1.5.0"
  },
  "autoload": {
    "psr-0": {
      "Zendesk\\API\\": "src/"
    }
  }
}`

My code in console:
`require 'vendor/autoload.php';
require 'vendor/autoload.php';
$subdomain = "me";
$username  = "me@me.com";
$token     = 'token';
$client = new ZendeskAPI($subdomain, $username);
`
Fatal error:  Class 'ZendeskAPI' not found in php shell code on line 1

echo getcwd();
=> /media/psf/Home/apps/zendesk_api_client_php

Unsure if I'm using the console correctly with this? thx, sam

**Comment by joseconsador** [comment]
@sam452 On our provided sample, this line https://github.com/zendesk/zendesk_api_client_php/blob/master/samples/getTickets.php#L4 aliases Zendesk\API\HttpClient as ZendeskAPI . Based on your code, it will fail to find a ZendeskAPI class, try using new Zendesk\API\HttpClient($subdomain, $username).

**Comment by sam452** [comment]
Yes, that should work but using your code in the link:
`include 'vendor/autoload.php';
$subdomain = 'example';
$username = 'me@me.com';
$token = "myTOKEN";
use Zendesk\API\HttpClient as ZendeskAPI;
$client = new Zendesk\API\HttpClient($subdomain, $username);`

Fatal error: Class 'ZendeskAPI' not found in php shell code on line 1
There's something I'm blind to, sam
`

**Comment by joseconsador** [comment]
@sam452 Reading back on your first comment, 

> I cloned the repo from github and used composer to install

If you're running your code from a clone, the client's files will be in `src/Zendesk/API/` and not under `vendor`.

The way to do it is, on your project add 
```
{
  "require": {
    "zendesk/zendesk_api_client_php": "dev-master"
  }
}
```

OR if you just want to try out the client like what you're doing now. On a new directory, do `composer require zendesk/zendesk_api_client_php`.

**Comment by hasnain03** [comment]
i am facing this error
Fatal error: Class 'Zendesk\API\HttpClient' not found in zendesk/samples/getTickets.php on line 16
kindly tell me whats is issue?
