### ISSUE TITLE
SSL peer verification disabled in Http.php

### ISSUE THREAD

**Issue by xiaoyongwu** [zendesk/zendesk_api_client_php#181]
Hi, 
Any specific reason that SSL peer verification is disabled for the API code? This would make it vulnerable to MITM attacks. It looks to me that we should make it always enabled instead.

**Comment by jwswj** [comment]
Hey @xiaoyongwu - it's a piece of the v2 we haven't modified since v1. We'll be revisiting it in the coming weeks to stop using curl directly for the oauth process.

**Comment by jwswj** [comment]
https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Http.php#L171 (just for reference)

**Comment by jwswj** [comment]
@xiaoyongwu https://github.com/zendesk/zendesk_api_client_php/issues/181 should remove this issue.
