### ISSUE TITLE
Update README to latest Zendesk client API

### ISSUE THREAD

**Issue by trashofmasters** [zendesk/zendesk_api_client_php#183]
Please update the README file to reflect the recent changes to the `dev-master` version of the codebase.

In particular the code examples do not reflect the change of `Zendesk\API\Client` to `Zendesk\API\HttpClient`:

```
Class 'Zendesk\API\Client' not found
```

More importantly there is no mention to the fact `token` in no longer considered a valid authentication method:

```
Invalid auth strategy set, please use `basic` or `oauth`
```

Thanks.

**Comment by jwswj** [comment]
Hi @trashofmasters - sorry for missing this. Resolved in https://github.com/zendesk/zendesk_api_client_php/pull/184

**Comment by jwswj** [comment]
Also wanted to note that token is still possible, it just falls under the basic auth type in v2.
