### ISSUE TITLE
Undefined property: Zendesk\API\Resources\Core\Search::$results

### ISSUE THREAD

**Issue by latheesan-k** [zendesk/zendesk_api_client_php#193]
I am using this api client in a laravel 4.2 project I have the following code:

    public function GetClient()
    {
        $client = new ZendeskAPI($this->zendesk['Subdomain'], $this->zendesk['Username']);
        $client->setAuth('basic', ['username' => $this->zendesk['Username'], 'token' => $this->zendesk['Token']]);
        return $client;
    }

And I use it like this:

    $client = $this->GetClient();
    $query = 'type:organization name:"'.$zendesk_organisation_name.'"';
    $params = array(
        'query' => $query
    );
    $organisations = $client->search($params);

This gives me the following error: `Undefined property: Zendesk\API\Resources\Core\Search::$results`

I have not been able to track down exactly where or how this error is occurring. This code worked fine before until I recently did a `composer update`. Has there been any major breaking changes?

**Comment by jwswj** [comment]
There has been a major breaking change as we moved from v1 to v2. I'd recommend locking your composer file to the `1.*` to get this working again, then looking at upgrading to the v2 branch as it has much better error handing. 

In the v2 world your code looks like:
```
$client = $this->GetClient();
$query = 'type:organization name:"'.$zendesk_organisation_name.'"';
$organisations = $client->search()->find($query);
```

We're working on an upgrade guide to help people move from v1 to v2.

**Comment by jwswj** [comment]
Looks like you also got this answered on our community forums - https://support.zendesk.com/hc/en-us/community/posts/205432517-PHP-API-Error-Undefined-property-Zendesk-API-Resources-Core-Search-results?page=1#community_comment_207608577
