### ISSUE TITLE
Make the API for IDE friendly.

### ISSUE THREAD

**Issue by whitefire** [zendesk/zendesk_api_client_php#2]
First of all: Thank you for taking the time to make this API.

Being an avid PhpStorm-user, I miss my code-completions. Both for API-calls and the entities returned.

I realize this might make the API-client less maintainable, but ease and comfort of use is also important.

I will be using this client extensively for a web-project in the near-future. I might open a pull-request adding IDE-friendlyness, but I would be very happy if you could give some pointers how to go about it! :)

**Comment by ggrossman** [comment]
@mikealmond would you be interested in submitting a PR to merge your phpDocumentor changes into master?

**Comment by ggrossman** [comment]
@mikealmond's changes were merged as https://github.com/zendesk/zendesk_api_client_php/pull/32
