### ISSUE TITLE
PHP Fatal Error: Call to a member function getReasonPhrase() on a non-object

### ISSUE THREAD

**Issue by mtibben** [zendesk/zendesk_api_client_php#201]
Using 04e31fba we're seeing the following error being thrown inside the Zendesk library:

```
vendor/zendesk/zendesk_api_client_php/src/Zendesk/API/Exceptions/ApiResponseException.php:22
Call to a member function getReasonPhrase() on a non-object
```

Given that it's a fatal error occurring inside the library we can't see the context in which this is occuring

**Comment by joseconsador** [comment]
@mtibben Kindly provide us with more details so we can look further into the issue. What endpoints/methods were you trying to use? Are you able to make the sample (https://github.com/zendesk/zendesk_api_client_php/blob/master/samples/getTickets.php) work? Thanks
