### ISSUE TITLE
Recent v2.0.* releases not available via Packagist

### ISSUE THREAD

**Issue by mtibben** [zendesk/zendesk_api_client_php#211]
Your recent v2.0.* releases are not available via Packagist. You may need to update your packagist  github webhook

https://packagist.org/packages/zendesk/zendesk_api_client_php

**Comment by dragonwize** [comment]
I noticed this as well. Forced to downloading the newest stable version as it not available in packagist.

**Comment by miogalang** [comment]
Hi Guys,

Will reach out to the owners and see if I can get the webhook updated. I'll let you guys know after I get in touch with them.

Thanks,

Mio

**Comment by miogalang** [comment]
https://github.com/zendesk/zendesk_api_client_php/pull/214 This should fix it.

**Comment by miogalang** [comment]
It seems there is a version mismatch in the composer.json file. Fixing the issue in https://github.com/zendesk/zendesk_api_client_php/pull/214

**Comment by miogalang** [comment]
v2.0.3 now available via packagist. Closing this out.
