### ISSUE TITLE
Recommend an other verison than dev-master

### ISSUE THREAD

**Issue by jarnheimer** [zendesk/zendesk_api_client_php#212]
Including *dev-master* feels unstable. 

```No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license. require.doctrine/dbal : unbound version constraints (*) should be avoided require.zendesk/zendesk_api_client_php : unbound version constraints (dev-master) should be avoided```

**Comment by miogalang** [comment]
Hi @jarnheimer there seems to be a problem with syncing of the versions in packagist. This seems to be related to https://github.com/zendesk/zendesk_api_client_php/issues/211

I will try to sync these up today.

Closing this issue and moving to the other one.
