### ISSUE TITLE
Filter and search request 

### ISSUE THREAD

**Issue by rafaelfoster** [zendesk/zendesk_api_client_php#217]
Hi There,

How do I filter the request?
I want to filter tickets creating (greather than) date like:

Ticket create more than 2015-09-01 and less than 2015-10-01;

How can I do that?
$tickets = $zendesk->tickets()->findAll(["created_at" => "2015-09"]);

And the search API is not documented, how do I use it?
There's some documentation to guide me?

I appreciate that!

**Comment by RaFeNiX** [comment]
Hi Rafael, try created_at>2015-01-01

Em 26/10/2015 10:50, Rafael Foster <notifications@github.com> escreveu:
Hi There,

How do I filter the request?
I want to filter tickets creating (greather than) date like:

Ticket create more than 2015-09-01 and less than 2015-10-01;

How can I do that?
$tickets = $zendesk->tickets()->findAll(["created_at" => "2015-06"]);

And the search API is not documented, how do I use it?
There's some documentation to guide me?


I appreciate that!




---
Reply to this email directly or view it on GitHub:
https://github.com/zendesk/zendesk_api_client_php/issues/217

**Comment by rafaelfoster** [comment]
I've done this befere without success.
The organization field is being filtered perfectly, but creation date doesn't.

If try this codes bellow:

 $tickets = $zendesk->tickets()->findAll(["created_at" => "2015-01-07", "organization_id" => $orgID]);

and

 $tickets = $zendesk->tickets()->findAll(["created_at>2015-01-07", "organization_id" => $orgID]);

also

$tickets = $zendesk->tickets()->findAll(["created_at>2015-01-07"]);

print_r($tickets);
  ....

It returns me all tickets, like:
  [created_at] => 2015-06-03T13:52:39Z
  [updated_at] => 2015-07-17T20:05:29Z
  [type] => problem
  [subject] => "loren ipson"
  etc....

Any idea?

**Comment by RaFeNiX** [comment]
Hi rafael,
i just figured out you're using the findAll() from tickets().In this case i would use ## $teste = $client->search(['query'=>"type:ticket created_at>2015-01-07"]); ##
try it, working here

Date: Mon, 26 Oct 2015 08:23:05 -0700

**Comment by rafaelfoster** [comment]
Thanks for your response @RaFeNiX 

Unfortunally, it still not working.

I've copied your entire line and add it to my code.
The API doesn't returns me any erros.

But it return this: 

Zendesk\API\Resources\Core\Search Object
(
    [resourceName:protected] => search
    [objectName:protected] => search
    [objectNamePlural:protected] => searches
    [client:protected] => Zendesk\API\HttpClient Object
        (
            [auth:protected] => Zendesk\API\Utilities\Auth Object
                (
                    [authStrategy:protected] => basic
                    [authOptions:protected] => Array
                        (
                            [username] => helpdesk@EXAMPLE.com.br
                            [token] => 8Gasdsadsada4GCBAuRiRLitJCcj6wbHNLWPQEhhTcl3epIfWK
                        )

                )

            [subdomain:protected] => EXAMPLE
            [username:protected] => helpdesk@EXAMPLE.com.br
            [scheme:protected] => https
            [hostname:protected] => zendesk.com
            [port:protected] => 443
            [apiUrl:protected] => https://EXAMPLE.zendesk.com:443/api/v2/
            [apiVer:protected] => v2
            [sideload:protected] => 
            [debug:protected] => Zendesk\API\Debug Object
                (
                    [lastRequestBody] => 
                    [lastRequestHeaders] => Array
                        (
                            [Host] => Array
                                (
                                    [0] => EXAMPLE.zendesk.com
                                )

                            [Accept] => Array
                                (
                                    [0] => application/json
                                )

                            [Content-Type] => Array
                                (
                                    [0] => application/json
                                )

                            [User-Agent] => Array
                                (
                                    [0] => ZendeskAPI PHP 2.0.0
                                )

                        )

                    [lastResponseCode] => 200
                    [lastResponseHeaders] => Array
                        (
                            [Server] => Array
                                (
                                    [0] => nginx
                                )

                            [Date] => Array
                                (
                                    [0] => Mon, 26 Oct 2015 16:28:05 GMT
                                )

                            [Content-Type] => Array
                                (
                                    [0] => application/json; charset=UTF-8
                                )

                            [Content-Length] => Array
                                (
                                    [0] => 5349
                                )

                            [Connection] => Array
                                (
                                    [0] => keep-alive
                                )

                            [Status] => Array
                                (
                                    [0] => 200 OK
                                )

                            [X-Zendesk-API-Version] => Array
                                (
                                    [0] => v2
                                )

                            [X-Frame-Options] => Array
                                (
                                    [0] => SAMEORIGIN
                                )

                            [Strict-Transport-Security] => Array
                                (
                                    [0] => max-age=31536000;
                                )

                            [X-UA-Compatible] => Array
                                (
                                    [0] => IE=Edge,chrome=1
                                )

                            [ETag] => Array
                                (
                                    [0] => W/"46af5d3faec10f397298da25788aa75f"
                                )

                            [Cache-Control] => Array
                                (
                                    [0] => must-revalidate, private, max-age=0
                                )

                            [X-Zendesk-Origin-Server] => Array
                                (
                                    [0] => app13.pod4.sac1.zdsys.com
                                )

                            [X-Request-Id] => Array
                                (
                                    [0] => 099b76e0-c9d2-4b66-cb0a-b8ca3a61dd58
                                )

                            [X-Runtime] => Array
                                (
                                    [0] => 0.699089
                                )

                            [X-Rack-Cache] => Array
                                (
                                    [0] => miss
                                )

                            [X-Zendesk-Request-Id] => Array
                                (
                                    [0] => b23edeab94d1ca72b9c912adas
                                )

                            [X-Content-Type-Options] => Array
                                (
                                    [0] => nosniff
                                )

                        )

                    [lastResponseError] => 
                )

            [guzzle] => GuzzleHttp\Client Object
                (
                    [config:GuzzleHttp\Client:private] => Array
                        (
                            [handler] => GuzzleHttp\HandlerStack Object
                                (
                                    [handler:GuzzleHttp\HandlerStack:private] => Closure Object
                                        (
                                            [static] => Array
                                                (
                                                    [default] => Closure Object
                                                        (
                                                            [static] => Array
                                                                (
                                                                    [default] => GuzzleHttp\Handler\CurlMultiHandler Object
                                                                        (
                                                                            [factory:GuzzleHttp\Handler\CurlMultiHandler:private] => GuzzleHttp\Handler\CurlFactory Object
                                                                                (
                                                                                    [handles:GuzzleHttp\Handler\CurlFactory:private] => Array
                                                                                        (
                                                                                            [0] => Resource id #90
                                                                                        )

                                                                                    [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 50
                                                                                )

                                                                            [selectTimeout:GuzzleHttp\Handler\CurlMultiHandler:private] => 1
                                                                            [active:GuzzleHttp\Handler\CurlMultiHandler:private] => 0
                                                                            [handles:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
                                                                                (
                                                                                )

                                                                            [delays:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
                                                                                (
                                                                                )

                                                                            [_mh] => Resource id #93
                                                                        )

                                                                    [sync] => GuzzleHttp\Handler\CurlHandler Object
                                                                        (
                                                                            [factory:GuzzleHttp\Handler\CurlHandler:private] => GuzzleHttp\Handler\CurlFactory Object
                                                                                (
                                                                                    [handles:GuzzleHttp\Handler\CurlFactory:private] => 
                                                                                    [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 3
                                                                                )

                                                                        )

                                                                )

                                                            [parameter] => Array
                                                                (
                                                                    [$request] => 
                                                                    [$options] => 
                                                                )

                                                        )

                                                    [streaming] => GuzzleHttp\Handler\StreamHandler Object
                                                        (
                                                            [lastHeaders:GuzzleHttp\Handler\StreamHandler:private] => Array
                                                                (
                                                                )

                                                        )

                                                )

                                            [parameter] => Array
                                                (
                                                    [$request] => 
                                                    [$options] => 
                                                )

                                        )

                                    [stack:GuzzleHttp\HandlerStack:private] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => http_errors
                                                )

                                            [1] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => allow_redirects
                                                )

                                            [2] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => cookies
                                                )

                                            [3] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => prepare_body
                                                )

                                        )

**Comment by RaFeNiX** [comment]
try this simple code.

include("./vendor/autoload.php");
use Zendesk\API\Client as ZendeskAPI;
$subdomain = "";
$username  = "";
$token     = "";
$client = new ZendeskAPI($subdomain, $username);
$client->setAuth('token', $token);

$tesrte = $client->search(['query'=>"type:ticket created_at>2015-10-20"]);

echo json_encode($tesrte);

**Comment by rafaelfoster** [comment]
The json returns me empty.

Hey, maybe it could be the last version of API? 
I've cloned this repo. 
Which version are you using?

![error_zenapi](https://cloud.githubusercontent.com/assets/4605083/10736790/f9d87514-7bf5-11e5-8ae5-9fb0a2825980.jpg)


![error_zenapi2](https://cloud.githubusercontent.com/assets/4605083/10736882/6b6657a0-7bf6-11e5-9e20-db7b008f2c76.jpg)

**Comment by miogalang** [comment]
Hi @rafaelfoster 

On version 2 of the client things have changed quite a bit.

To achieve what you want, you would want a snippet like 

```
$response = $client->search()->find('type:ticket created>=2015-09-01 created<2015-10-01');
```
Search is now a resource you can make calls on, similar to a ticket or a user. We wanted to keep this pattern consistent.

For more documentation on using search there is https://developer.zendesk.com/rest_api/docs/core/search and https://support.zendesk.com/hc/en-us/articles/203663226

And a pro tip to test your query string easily is to try it out in the zendesk ui.
<img width="1270" alt="screen shot 2015-10-28 at 10 20 54 am" src="https://cloud.githubusercontent.com/assets/1471573/10778140/b62ad1c2-7d5d-11e5-8d89-d8a31e744ce9.png">

It also seems like you are using the version 1 way of making a search, if you are upgrading, there is a handy [upgrade guide](https://github.com/zendesk/zendesk_api_client_php/wiki/Upgrading-from-v1-to-v2) that can help you upgrade.

Please let me know if this works.

**Comment by rafaelfoster** [comment]
Yeah! That's working now @miogalang 

I really appreciate that!

Thanks for your help too @RaFeNiX
