### ISSUE TITLE
Documentation of return values

### ISSUE THREAD

**Issue by netbrothers-tr** [zendesk/zendesk_api_client_php#218]
In some places the return annotations simply consist of the word "mixed". In my opinion, should it matter, this isn't enough.

Example: https://github.com/zendesk/zendesk_api_client_php/blob/v2.0.7/src/Zendesk/API/Resources/Core/Tickets.php#L191

**Comment by miogalang** [comment]
:+1:  Agree. This should be something more descriptive. Will add this to the list of technical debt. Not sure how soon we can get to it though.

**Comment by netbrothers-tr** [comment]
@miogalang Thanks for your response. I really appreciate the client and I will patiently wait for updates in this field.

**Comment by miogalang** [comment]
Closing this. Solved with PR from https://github.com/zendesk/zendesk_api_client_php/pull/254

**Comment by netbrothers-tr** [comment]
Thanks guys! :thumbsup:
