### ISSUE TITLE
Regarding new ticket creation

### ISSUE THREAD

**Issue by kenwalker08** [zendesk/zendesk_api_client_php#22]
Hello, I am using the new ticket creation code as follows but it is showing error "Trying to get property of non-object"...Please help.

<?PHP include("zendesk.php");
$apiKey="My client API";
$user="My client User Name";
$subDomain="ideausa";
$zendesk = new Zendesk($apiKey, $user, $subDomain, $suffix = '.json', $test = false);
$arr     = array("z_subject"=>"Help, my device is off!",
	   "z_description"=>"help I need some help",
	   "z_recipient"=>"danish@ideausa.us",
	   "z_name"=>"Jacks Ferro",
	   "z_requester"=>"jacksferro27@gmail.com"
	  );
$create  = json_encode(array('ticket' => array('subject' => $arr['z_subject'], 'description' => $arr['z_description'], 'requester' => array('name' => $arr['z_name'], 'email' => $arr['z_requester']))), JSON_FORCE_OBJECT);
$data    = $zendesk->call("/tickets", $create, "GET");

print "hello test".$data->ticket->id;

$test = $zendesk->test();

print "\n";
?>

Thanks in advance.

**Comment by mikecurry74** [comment]
Same issue here, installed via Composer...

**Comment by bvisness** [comment]
Same here as well. "Class 'Zendesk\Api\Client' not found"...
