### ISSUE TITLE
Retrieve tickets requested by a user

### ISSUE THREAD

**Issue by massreuy** [zendesk/zendesk_api_client_php#222]
How to retrieve tickets requested by a specific user in Zendesk PHP API Client V2? 

In previous version I used this way

``` php
$tickets = $client->users($requesterId)->tickets()->findAll()
```

But in V2 there is no method called tickets available in Zendesk\API\Resources\Core\Users.

There is no reference about it in upgrade guide.

**Comment by joseconsador** [comment]
Hi @massreuy 
  If you're referring to end-user tickets you can do it this way:

```php
$tickets = $client->users($requesterId)->requests()->findAll()
```php

For agents though, we haven't covered that part yet. Thank you for notifying us and we'll be sure to discuss this in our coming meeting next week.

Alternatively, if you'd like to submit your own Pull Request, you may do so. We do appreciate them! https://github.com/zendesk/zendesk_api_client_php#note-on-patchespull-requests 

Regards,
Jose

**Comment by ghermans** [comment]
@joseconsador do you have any update regarding this?
