### ISSUE TITLE
Satisfaction documentation

### ISSUE THREAD

**Issue by antoscarface** [zendesk/zendesk_api_client_php#224]
Hi,

Is there some documentation for satisfaction call? I want to manage the ability to vote a ticket as "good" or "bad", with also a comment.

I'm trying to write this:

```
$this->client->satisfactionRatings()->create([
			'satisfaction_rating' => [
				'score' => 'good',
				'comment' => 'Awesome!',
				'ticket_id' => 23,
				'requester_id' => 2741620557
			]
		]);
```

But, I receive this error:

> Client error response [url] https://yithemes1432719252.zendesk.com/api/v2/satisfaction_ratings.json [http method] POST [status code] 404 [reason phrase] Not Found [details] {“error”:”InvalidEndpoint”,”description”:”Not found”}

I see also in the [zendesk documentation](https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings#create-a-satisfaction-rating) that the url for request should be `POST /api/v2/tickets/{ticket_id}/satisfaction_rating.json` and it's not that one shown on error message.

Is there something I'm wrong or should there be some bug?

I hope is all clear, thanks.

**Comment by antoscarface** [comment]
I fixed with thi https://github.com/zendesk/zendesk_api_client_php/pull/225

**Comment by joseconsador** [comment]
@antoscarface You're totally right. The endpoint we're hitting with the API is incorrect. We're now in the process of reviewing your PR so it should be merged in a day or two. Thanks!

**Comment by antoscarface** [comment]
Thank you so much! :)
