### ISSUE TITLE
How to stablish autoload/require?

### ISSUE THREAD

**Issue by mundoEarth** [zendesk/zendesk_api_client_php#228]
in my /samples/getTickets.php file here is the full code 

<?php
require "../../../php/vendor/autoload.php";

use Zendesk\API\HttpClient as ZendeskAPI;

/**
- Replace the following with your own.
  */
  $subdomain = "subdomain";
  $username  = "userme";
  $token     = "tokentokentoken12345678910";

$client = new ZendeskAPI($subdomain, $username);
$client->setAuth('basic', ['username' => $username, 'token' => $token]);

try {
    // Get all tickets
    $tickets = $client->tickets()->findAll();
    // Create a new ticket
    $newTicket = $client->tickets()->create(array(
        'subject'  => 'The quick brown fox jumps over the lazy dog',
        'comment'  => array(
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
        ),
        'priority' => 'normal'
    ));

```
print_r($tickets);
print_r($newTicket);
```

} catch (\Zendesk\API\Exceptions\ApiResponseException $e) {
    echo 'Please check your credentials. Make sure to change the $subdomain, $username, and $token variables in this file.';
}

the composer is installed in path C:\xampp\php. 
And It gives me a message "Fatal error: Class 'Zendesk\API\HttpClient' not found"

**Comment by joseconsador** [comment]
@mundoEarth Where is your "vendor" directory located? After you run `composer install` on the root directory, you shouldn't have to change the first line of the sample file.
