### ISSUE TITLE
cannot create ticket

### ISSUE THREAD

**Issue by elviskudo** [zendesk/zendesk_api_client_php#231]
I have a issue about create ticket

after i submit form, data created like this

```
array(8) {
  ["subject"]=>
  string(10) "testing #1"
  ["type"]=>
  string(8) "incident"
  ["description"]=>
  string(0) ""
  ["priority"]=>
  string(6) "urgent"
  ["status"]=>
  string(4) "open"
  ["assigned_id"]=>
  string(9) "*****"
  ["requester_id"]=>
  string(9) "***********"
  ["group_id"]=>
  string(8) "********"
}
```

but when $client->tickets()->create($data);

result is below

```
Client error: `POST https://mydomain.zendesk.com/api/v2/tickets.json` resulted in a `422 Unprocessable Entity` response:
{"error":"RecordInvalid","description":"Record validation errors","details":{"base":[{"description":"Description: cannot (truncated...)
[details] {"error":"RecordInvalid","description":"Record validation errors","details":{"base":[{"description":"Description: cannot be blank","error":"BlankValue"}]}}

```

in 3 days ago, everything is normal, whats happen now?
thanks

**Comment by joseconsador** [comment]
@elviskudo 
Based on the error response, could you check the payload you are sending if the "description" field has any value?

**Comment by karl-casas777** [comment]
@elviskudo Description is required and cannot be blank. Please refer on this api documentation https://developer.zendesk.com/rest_api/docs/core/tickets#create-ticket. Description is used to create the comment.
