### ISSUE TITLE
inconsistent methods in Organizations class.

### ISSUE THREAD

**Issue by devanes** [zendesk/zendesk_api_client_php#245]
In the Zendesk\API\Resources\Core\Organizations class the PHPDoc suggests methods calles \d
**organizationMemberships** and **organizationSubscriptions**, but in the getValidSubResources method, these are called **memberships** and **subscriptions**.

Not only does this result in autocompleted methods in my IDE which don't work, but also using the shorter names is inconsistent with the actuals names uses in the API itself and in for example the Zendesk\API\Resources\Core\Users class (where the long version is used).

**Comment by miogalang** [comment]
Let's talk about this in https://github.com/zendesk/zendesk_api_client_php/issues/247. Closing this so we can have one issue for this.
