### ISSUE TITLE
Wrong return type

### ISSUE THREAD

**Issue by devanes** [zendesk/zendesk_api_client_php#247]
The autocomplete method in src/Zendesk/API/Resources/Core/Organizations.php is said (in phpDoc) to return an array. Instead it returns a stdClass object (containing an array of organizations). This results in IDE errors.

**Comment by TemirkhanN** [comment]
There is huge amount of wrong return types that shall be fixed after
[this fix](https://github.com/zendesk/zendesk_api_client_php/pull/234/commits/7407dddb1acace419a4f3fa18be37896f0c16f98)

**Comment by miogalang** [comment]
Hi sorry for the delated reply, I am seeing a bunch of these errors. I have created a task in our backlog to take care of all of these and check all the resource classes. Hopefully we can get to it soon.

**Comment by miogalang** [comment]
Closing this. Solved in https://github.com/zendesk/zendesk_api_client_php/pull/258 and https://github.com/zendesk/zendesk_api_client_php/pull/254
