### ISSUE TITLE
Multiple Attachments?

### ISSUE THREAD

**Issue by joeelizondo** [zendesk/zendesk_api_client_php#25]
It's not clear how to use this api client to add multiple attachments to a ticket, or if its even possible. My attempts result in only the last file actually getting attached. Has anyone been able to do this and if so do you mind sharing how?

**Comment by hiaik** [comment]
Hi @joeelizondo 

Although in code sample provided we have this doc:
     * Optional:
     *    'optional_token' - an existing token
     *        'name' - preferred filename

In the real code we have this: 
if (isset($params['token'])) {
            $queryParams['token'] = $params['token'];
        }


In conclusion, 

RE: adding multiple attachments to one comment of ZD ticket

<?php

use Zendesk\API\HttpClient as ZendeskAPI;

class ZDTEST
{

    public function execute()
    {
        // https://github.com/zendesk/zendesk_api_client_php
        // run "php composer.phar require zendesk/zendesk_api_client_php" from LSS dir

        $subdomain = "";
        $username = "";
        $token = ""; // replace this with your token

        $ticket_id = 2600;

        $client = new ZendeskAPI($subdomain);
        $client->setAuth('basic', ['username' => $username, 'token' => $token]);

        $sqlFiles = glob($this->directory . '/*.png');
        $upload_token = '';

        foreach ($sqlFiles as $sqlFile) {
            $params = array(
                'file' => $this->directory . basename($sqlFile),
                'type' => 'image/png',
                'name' => basename($sqlFile) // Optional parameter, will default to filename.ext
            );


            // multiple attachments
            // persist token https://github.com/zendesk/zendesk_api_client_php/issues/25
            if (isset($upload_token)) {
                **$params['token']** = $upload_token;
            }

            $attachment = $client->attachments()->upload($params);
            $upload_token = $attachment->upload->token;
        }

        $client->tickets()->update($ticket_id, [
            'priority' => 'high',
            'comment' => [
                'body' => 'TEST',
                'uploads' => [$upload_token],
                'public' => false
            ]
        ]);
    }
}
