### ISSUE TITLE
Attachement for an article

### ISSUE THREAD

**Issue by princebabay** [zendesk/zendesk_api_client_php#263]
Hello , I'd like to attach an attachment to an article.

how to do ?

Thanks !

**Comment by kcasas** [comment]
@princebabay Please refer to this link https://support.zendesk.com/hc/en-us/articles/223137947-Attach-files-via-API. There are two endpoints to achieve this. You need to first upload the attachment and then attach it to the comment. Like so

```
$attachment = $client->attachments()->upload([
    'file' => getcwd().'/sample.jpg',
    'type' => 'image/jpg',
    'name' => 'sample.jpg'
]);

$token = $attachment->upload->token;
$ticket = $client->tickets()->create([
    'subject' => 'test ticket attachment',
    'comment' => [
        'body'      => 'this is a description',
        'uploads'   => [$token]
    ]
]);
```
