### ISSUE TITLE
Error completing request [URL] --- [http method] GET [body]

### ISSUE THREAD

**Issue by ZeusBeard** [zendesk/zendesk_api_client_php#264]
When trying to access the Zendesk API it keeps failing, i can use guzzle to access the rest API fine, it just appears to be whenever i try and use the directed method.

You can see my example below

![image](https://cloud.githubusercontent.com/assets/21336008/18088452/ae0f4102-6eb2-11e6-9058-91d6503e428f.png)

**Comment by druizfr** [comment]
Hi Zeus,
I'm having the same issue over here. Did you manage to solve it?

**Comment by druizfr** [comment]
Hi Zeus,
Removing the trys it return me the real issue. Error 60 in cURL and fixed it with this: http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate
