### ISSUE TITLE
Count and results inconsistent in return object

### ISSUE THREAD

**Issue by netbrothers-tr** [zendesk/zendesk_api_client_php#265]
I am using the client among other things to retrieve open tickets for a specific requester. I'm using the [Search API](https://developer.zendesk.com/rest_api/docs/core/search) for that. Here's a simple code snippet for illustration purposes.

```
$query = 'type:ticket status:open requester_id:' . $requesterId;
$ticketsFound = $zendeskClient->search()->find($query);
```

Sometimes I receive an (unmodified) return object that looks like this.

```
stdClass Object (
     [results] => Array ( )
     [facets] =>
     [next_page] =>
     [previous_page] =>
     [count] => 1
)
```

Thus, the count conflicts with the actual results. Is this a known issue with Zendesk or is this the intended behaviour?

I am using the [latest version](https://github.com/zendesk/zendesk_api_client_php/commit/9029142bdc33f47e40aac2654e9f4a214ec437d4) at present.

**Comment by karl-casas777** [comment]
@netbrothers-tr Can't seem to reproduce this as of the moment. Can you try it again and if the problem persist provide me with more detail. Hope this is already fixed though.

**Comment by netbrothers-tr** [comment]
@karl-casas777 Thank you for your efforts to reproduce the problem! As a workaround, I'm not anymore relying on the count property. Since nobody is confirming this, I think it's best to close the issue for now. I also thought of it being a caching quirk of Zendesk itself.
