### ISSUE TITLE
How to create a ticket as end-user

### ISSUE THREAD

**Issue by achharsingh** [zendesk/zendesk_api_client_php#270]
Hello,

I'm using the $client->tickets()->create( $ticketParams ) method authenticated via agent credentials.

But i need to create a ticket as end user.

Is there any method which opens a ticket as end-user.

Thanks

**Comment by MatthewPattell** [comment]
Hello.
Use this:
`
$client->tickets()->create([
            'requester_id'=> $end_user_id, // <-- end-user id
            'subject'  => $params['subject'],
            'comment'  => [
                    'body' => $params['message'],
                    'uploads' => $params['attachments_token']
            ],
            'priority' => $params['priority']
]);
`

**Comment by ghermans** [comment]
@MatthewPattell  thanks for your solution, do you maybe also have an idea how to get the requester_id ?
