### ISSUE TITLE
TicketComments is not usable

### ISSUE THREAD

**Issue by NinoSkopac** [zendesk/zendesk_api_client_php#272]
Not imported in `src/Zendesk/API/HttpClient.phpsrc/Zendesk/API/HttpClient.php`.

**Comment by NinoSkopac** [comment]
I haven't tested it, but I'd assume the same problem is present for some other calls.

**Comment by ghermans** [comment]
@NinoSkopac, @joseconsador  any update regarding this?

**Comment by NinoSkopac** [comment]
@ghermans Ship it

**Comment by ghermans** [comment]
@NinoSkopac ok, are you planning to make an example file in the samples folder?

**Comment by NinoSkopac** [comment]
@ghermans Sure thing, will do it later today or tomorrow.

**Comment by ghermans** [comment]
@NinoSkopac i added the example #287, so you can close this can be marked as solved i guess ?
