### ISSUE TITLE
ApiResponseException should have a getter for the original Guzzle RequestException.

### ISSUE THREAD

**Issue by BrunoDeBarros** [zendesk/zendesk_api_client_php#277]
I've just been experiencing some connectivity issues on a client's server and noticed that the Zendesk ApiResponseException does not provide for a way to access the original response exception object, which means I have no way to write clean error handling code for errors that aren't related to Zendesk or its servers.

You already receive the Guzzle RequestException in the `__construct()`, it would be quite straightforward to just store it in a variable and make it accessible like you do with `getErrorDetails()`.

Happy to write a PR for this if it's something you'd be open to merging!

**Comment by joseconsador** [comment]
@BrunoDeBarros Please do submit a PR, we'd be happy to review and merge it. Thanks!

**Comment by kcasas** [comment]
@BrunoDeBarros @joseconsador Created a pull request for this #291. No need to create a variable for the original Exception, PHP already supports stacking of previous exceptions. When creating new exceptions, pass the original exception as the 3rd parameter unto the constructor and it would be available by calling `$e->getPrevious()`.

**Comment by BrunoDeBarros** [comment]
Awesome, thank you so much for doing this! :smile: It's very much appreciated.
