### ISSUE TITLE
assign tickets to group

### ISSUE THREAD

**Issue by ghermans** [zendesk/zendesk_api_client_php#288]
Guys,

i am having an issue with the code below when assigning a ticket to a group.
The ticket gets created however it is always assigned to the wrong group.

```php
$newTicket = $client->tickets()->create(array(
    'type' => 'problem',
    'tags'  => array('demo', 'testing', 'api', 'zendesk'),
    'subject'  => 'Assigned to sales group',
    'group_id' => 25983169,
    'comment'  => array(
                'body' => 'Lorem ipsum dolor sit amet.'
                 ),
    'priority' => 'normal',
    ));
```

**Comment by joseconsador** [comment]
@ghermans It seems to work fine for me. I added a (PR)[https://github.com/zendesk/zendesk_api_client_php/pull/290] to verify. Were you able to get more info on this?

**Comment by ghermans** [comment]
@joseconsador i have created a ticket a couple days ago regarding this issue, one of the zendesk support enigneers (level 2) told me yesterday the following:


> 
> Thank you! We just reproduced the issue you encountered and allow us some time to check our logs and other configurations to identify the cause of this behaviour.
> 
> You may see this ticket's status as onhold but, rest assured that we are working on it.
> 

if i have more info i will post it here.
