### ISSUE TITLE
 Error completing request

### ISSUE THREAD

**Issue by julzpalomiano** [zendesk/zendesk_api_client_php#289]
I downloaded (https://github.com/zendesk/zendesk_api_client_php) using composer and copy paste the basic operation there but it seems that even if I inputted the correct subdomain, username, and token I always come up with the error saying that

Error completing request [url] https://xxx.zendesk.com/api/v2/tickets.json [http method] GET [body] in

**Comment by joseconsador** [comment]
@julzpalomiano Could you paste the error here? It's cut-off.

**Comment by julzpalomiano** [comment]
@joseconsador here you go..

Uncaught Zendesk\API\Exceptions\ApiResponseException: Error completing request [url] https://julz.zendesk.com/api/v2/tickets.json [http method] GET [body] in C:\xampp\htdocs\Dropbox\practice\zendeskapi\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Http.php:89 Stack trace: #0 C:\xampp\htdocs\Dropbox\practice\zendeskapi\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\HttpClient.php(445): Zendesk\API\Http::send(Object(Zendesk\API\HttpClient), 'tickets.json', Array) #1 C:\xampp\htdocs\Dropbox\practice\zendeskapi\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Traits\Resource\FindAll.php(31): Zendesk\API\HttpClient->get('tickets.json', Array) #2 C:\xampp\htdocs\Dropbox\practice\zendeskapi\mclink.php(32): Zendesk\API\Resources\Core\Tickets->findAll() #3 {main} thrown in 



salamat :)

**Comment by joseconsador** [comment]
Can you give the output for:

```php
try {
  $response = $this->client->tickets()->findAll();
} catch (Zendesk\API\Exceptions\ApiResponseException $e) {
  var_dump($e->getMessage());
}

```

**Comment by julzpalomiano** [comment]
@joseconsador 

 "Error completing request [url] https://julz.zendesk.com/api/v2/tickets.json [http method] GET [body] "

**Comment by phongtranh** [comment]
I have same error, can you tell me what its happend?

**Comment by Polou** [comment]
Same problem here with php 5.6 : 
`Error completing request [url] https://eureciahelp.zendesk.com/api/v2/tickets.json?include=users,groups [http method] GET [body] `

**Comment by puyaalexxx** [comment]
Hi! When are you going to fix this issue? thanks

**Comment by kcasas** [comment]
Hi, we can't recreate this issue and concluded that it might be a problem with the development setup. I'm thinking problems with your local machine's virtual host. Any information that would help us debug this would be very much appreciated.

**Comment by kcasas** [comment]
@puyaalexxx It would also be possible that you have not changed the credentials for the sample. Take note that you also have to provide your own token.

**Comment by samgavinio** [comment]
For any one still experiencing this issue, this is often due to a curl misconfiguration in your host machine. We've made a change to this client's exception handling which should give you more context about the ApiResponseException you are getting.

Please update to at least v2.1.10 and inspect the context of the exception, as it should help you better debug the issue with your curl set-up.

Closing this one, please feel free to open a new one should you still find an issue with the client.
