### ISSUE TITLE
Async ticket creation support

### ISSUE THREAD

**Issue by FuzzyTree** [zendesk/zendesk_api_client_php#299]
According to the documentation, it's possible to create a ticket asynchronously. But I couldn't find this feature in the sdk. Is it supported?

https://developer.zendesk.com/rest_api/docs/core/tickets#create-ticket

> Ticket creation can sometimes take a while because of complex business rules. Asynchronous creation allows you to get the response back quickly and queues a background job to do the actual work.
> 
> To make an asynchronous request, simply add the parameter async in your request.
> 
> POST api/v2/tickets.json?async=true
> 
> As soon as the request is received, it returns a 202 Accepted. The response includes the new ticket id with a job_status JSON object. However, you may not be able to fetch the ticket until the job is done.

**Comment by miogalang** [comment]
solved: https://github.com/zendesk/zendesk_api_client_php/pull/302

Available as of v2.1.7

**Comment by FuzzyTree** [comment]
@miogalang Thank you!
