### ISSUE TITLE
Unable to merge users

### ISSUE THREAD

**Issue by shershennm** [zendesk/zendesk_api_client_php#308]
In [Zendesk\API\Resources\Core\Users](https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Resources/Core/Users.php) exists only one route for merge - users/me/merge.json.
There are no route with [this method](https://developer.zendesk.com/rest_api/docs/core/users#merge-users) for merging users

**Comment by shershennm** [comment]
Fix without breaking backward compatibility #309

**Comment by bretticus** [comment]
Attempting to use this form:

`$this->client->users($id1)->merge(['id' => $id2]);`

Currently, with v2.1.8, the API request requires:

`['user' => ['id' => {some id}]]`

However, when you send that as the merge parameter, it currently only gets by the hasKeys check...

```
if (! $this->hasKeys($params, $hasKeys)) {
            throw new MissingParametersException(__METHOD__, $hasKeys);
        }
```

If it's entered as `['id' => {some id}]`

However, that results in a Zendesk\API\Exceptions\ApiResponseException

**Comment by bretticus** [comment]
I tried commenting the hasKeys check out and I just realized that it still gets sent using the `/me/` form anyway (hence this pull request!)

Thanks for fixing this!

For now, I'll just call the URL via cURL.

**Comment by bretticus** [comment]
So far, I have tried:

```
$response = Http::send($client, sprintf('users/%d/merge.json', $id1),
       ['postFields' => ['user' => ['id' => $id2]], 'method' => 'PUT']
);
```
But now, I'm getting `422 Unprocessable Entity`

I can make the request via curl in console command. So strange!

**Comment by bretticus** [comment]
I found that by changing the user order, I was successful after all.
