### ISSUE TITLE
Zendesk error

### ISSUE THREAD

**Issue by pagedesigner** [zendesk/zendesk_api_client_php#311]
Hi im php developer and new to zendesk, i have recently got my account approved for developing purposes and was trying to connect to my account via php library, but im having issue, whenevr i try to connect it gives following error on local server as well as on remote server

Fatal error: Class 'Zendesk\API\Utilities\OAuth' not found in D:\xampp\htdocs\zendesk\samples\auth\oauth.php on line 14
 
i have consulted zendesk support and they requested to post here, im running php 5.6 and unable to resolve this issue. Plz help.

Thanks

**Comment by samgavinio** [comment]
Did you install the client via [composer](https://getcomposer.org/) as suggested by the readme? Running `composer install` should pull it in and generate the `vendor/autoload.php` file. Make sure you are referencing it's path correctly in your script:

```
include("../../vendor/autoload.php");
```

In general, `Fatal error: Class 'Something\Foo\Far` just means that the class you are trying to load hasn't been included by your autoloader.

**Comment by pagedesigner** [comment]
ok i downloaded fresh copy via composer and changed the autoload.php ref, it works but this error appeared https://www.screencast.com/t/qfGGmTKuE

**Comment by samgavinio** [comment]
@pagedesigner from the looks of this, you probably did not set the redirect URL correctly in your Zendesk's oauth client configuration. 

Have a look at this help center article:

https://support.zendesk.com/hc/en-us/articles/203663836-Using-OAuth-authentication-with-your-application
