### ISSUE TITLE
problem running composer require zendesk/zendesk_api_client_php

### ISSUE THREAD

**Issue by undentifiedkc** [zendesk/zendesk_api_client_php#317]
When i try to run composer require, it will prompt me below error instead, can i know how to overcome this issue?

  Problem 1
    - The requested package zendesk/zendesk_api_client_php No version set (parsed as 1.0.0) is satisfiable by zendesk/zendesk_api_client_php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by kcasas** [comment]
You might be running an outdated version of composer. Try running `composer self-update` first

**Comment by masterwebmonkey** [comment]
Why was this ticket closed... what was the resolution?
I have tried on windows 

OpenSSL 1.0.2n  
Composer version 1.6.2 
PHP 7.0.15 (cli) (built: Jan 17 2017 13:57:33) ( NTS )

and LINUX 
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Composer version @package_branch_alias_version@ (1.0.0-beta2)
OpenSSL 1.0.2g 

Same error

**Comment by masterwebmonkey** [comment]
To anyone else that happens to get this error 
try changing the "name" field in your composer.json
FROM "zendesk/zendesk_api_client_php"
TO "zendesk/zendesk_myclient"

**Comment by joseconsador** [comment]
@masterwebmonkey 
The ticket was closed because we didn't get any further response from @undentifiedkc . 
Can you paste the command and output here so we can help you?

**Comment by masterwebmonkey** [comment]
please update the description ... it currently has a LINK  to 

http://developer.zendesk.com/api-docs 
(this link is now 404)

I think a better place to send people would be   
https://developer.zendesk.com/rest_api
OR 
https://developer.zendesk.com/rest_api/docs/core/introduction

**Comment by ecoologic** [comment]
Done. ✅  A new release will be cut after we finish a new feature in development.
