### ISSUE TITLE
Is there a way to get Categories and Articles with Zendesk  ? 

### ISSUE THREAD

**Issue by Axheladini** [zendesk/zendesk_api_client_php#320]
I tried several ways to get categories and articles with Zendesk but i was not able to.

**Comment by samgavinio** [comment]
Hi @Axheladini if you are talking about helpcenter categories and articles you should be able to do this by doing something along the lines of

* $client->helpCenter->categories()->findAll();
* $client->helpCenter->articles()->findAll();

But this assumes that you have enabled the help center for your zendesk: https://support.zendesk.com/hc/en-us/articles/203664346-Getting-started-with-the-Help-Center
