### ISSUE TITLE
TicketMetrics class missing from HTTPClient.php

### ISSUE THREAD

**Issue by john-goss-zepler** [zendesk/zendesk_api_client_php#325]
Adding the TicketMetrics class to getValidSubResources() in HTTPClient.php fixes this.

**Comment by samgavinio** [comment]
@john-goss-zepler, the ticket metrics is actually namespaced with the tickets resource.

```
$metrics = $client->tickets($ticketId)->metrics()->findAll();
```

**Comment by samgavinio** [comment]
Closing this. If you have more concerns with the ticket metrics, feel free to open a new issue. Thanks.
