### ISSUE TITLE
Update primary address of a user by zendesk id

### ISSUE THREAD

**Issue by xserrat** [zendesk/zendesk_api_client_php#331]
Hi,

I'm trying to update the primary email address of a user but API adds the new email address as an additional email instead of primary.

I've tried to use the identities endpoint but I don't know the `userId` field, only `id` (the generated id).

Any idea?

Thank you so much!

**Comment by vumik** [comment]
Hi)
Write way is update user identities. You can search user and his user id by external_id or email or other identity.
