### ISSUE TITLE
Upgrade Guide Examples are broken

### ISSUE THREAD

**Issue by THC4k** [zendesk/zendesk_api_client_php#335]
The Upgrade guide Examples on https://github.com/zendesk/zendesk_api_client_php/wiki/Upgrading-from-v1-to-v2 are mostly the same code twice.

**Comment by jmramos02** [comment]
Hello!

The examples on the guide was intended, as most basic operations are really the same as the later

> Most basic operations are very similar. We’ve tried to keep them as consistent as possible between v1 and v2, but there are some slight differences
