### ISSUE TITLE
Can I get sections from Help Center?

### ISSUE THREAD

**Issue by n00el** [zendesk/zendesk_api_client_php#336]
Can I get sections from Help Center with this plugin?
And please, can you update the Help Center part, with find category, article, section by id?

**Comment by HuyCit** [comment]
I also have questions like you

**Comment by samgavinio** [comment]
Hi guys, only the core Zendesk API resources are well supported right now. I've created dev stories for some more HelpCenter resource support , but no promises on when we can get to them. Pull requests are welcome!
