### ISSUE TITLE
$client->users()->findAll() Not Returning All Users

### ISSUE THREAD

**Issue by KSilverman** [zendesk/zendesk_api_client_php#338]
I am trying to get a list of all my users, but the query is only limited to 100 users per page. When findAll() is called, it only retrieves page 2 because that is where api/v2/users.json redirects. I don't see a way to get the results from all the pages, or even an option to define a page or a role (for instance, if I wanted to get all the admins, agents, etc). Is there anyway to get around the 100 users query per page? Thanks!

EDIT: This is also doing the same thing for tickets, is there any way to get around this as well?

**Comment by samgavinio** [comment]
Hi :wave @KSilverman, please refer to the pagination section of the [readme](https://github.com/zendesk/zendesk_api_client_php#pagination). This behaves the same for the list endpoints.

You should also be able to pass-in a role parameter to the `findAll` method.

```
$client->users()->findAll([
    'per_page' => 10,
    'page' => 1,
    'role' => 'agent',
]);
```

**Comment by samgavinio** [comment]
Closing this one, but if you have more concerns with the usage feel free to add comments and ping me. Thanks.
