### ISSUE TITLE
Can't find user by ID

### ISSUE THREAD

**Issue by DeanWard** [zendesk/zendesk_api_client_php#348]
Hello,

I'm trying to get the name of the author for comments. Using the SDK I can't find a way to simply load user information based on ID as in the show user endpoint from the api (/api/v2/users/{id}.json)

I've tried searching with id:author_id but that returns nothing.

Is there something obvious I'm missing?

**Comment by jmramos02** [comment]
Have you tried sideloading? According to the readme:

`tickets = $client->tickets()->sideload(['users', 'groups'])->findAll();`

Just change it to 

`comments()->sideload(['users']);`

https://developer.zendesk.com/rest_api/docs/core/side_loading
