### ISSUE TITLE
Importing tickets fails when importing a ticket with multiple comments

### ISSUE THREAD

**Issue by paymonyau** [zendesk/zendesk_api_client_php#35]
Importing tickets fails when importing a ticket with multiple comments. Annoyingly the error message is so generic. The error in the end was the author ID was not valid. 

I'm assuming that the first comment has a fall back in the code to use the requester_id whereas the subsequent comments do not have a fall back as the comment could be from anyone.

**Comment by buheryfi** [comment]
@paymonyau can you share the code you are using and the error message you are seeing.  Perhaps we can take a look and find a resolution.

**Comment by atroche** [comment]
will close until @paymonyau gets back to us
