### ISSUE TITLE
Search Organizations

### ISSUE THREAD

**Issue by holtkamp** [zendesk/zendesk_api_client_php#350]
Users can be searched for [by name](https://github.com/zendesk/zendesk_api_client_php/blob/master/samples/users/searchUser.php), great!

I am trying to do the same for Organizations, this seems not possible using the [search](https://github.com/zendesk/zendesk_api_client_php/blob/f3681b06726a034905d093816467855acc8d2f60/src/Zendesk/API/Resources/Core/Organizations.php#L137) function. Should the [autocomplete](https://github.com/zendesk/zendesk_api_client_php/blob/f3681b06726a034905d093816467855acc8d2f60/src/Zendesk/API/Resources/Core/Organizations.php#L106) function be used for this?

And what if I want to search by a specific Organization field?

**Comment by kcasas** [comment]
@holtkamp Yes, you can use the autocomplete functionality for the search.

**Comment by holtkamp** [comment]
>And what if I want to search by a specific Organization field?

For example, we have Custom Organisation Fields `city` and `category`, etc.
