### ISSUE TITLE
Static Http::send() calls prevent SDK from being customized

### ISSUE THREAD

**Issue by brstgt** [zendesk/zendesk_api_client_php#360]
If you would replace Http::send() by a handler (simply a configurable callable) one would be able to use any arbitrary transport (not only guzzle) and even execute async requests, e.g. with Guzzles sendAsync or even a custom implementation.

That's exactly what I am trying to do. The only way to do this right now is to either mess in the source code or to autoload my own implementation of \Zendesk\API\Http. Neither is a good option.

**Comment by brstgt** [comment]
No updates here? It should be not so complicated to do that.
Using static coupling of components is a deadly sin. Really!

**Comment by ecoologic** [comment]
Hi,

 thank you for your request,
are you still interested in a solution for this issue?

**Comment by brstgt** [comment]
Wow. 7 years (!!!) after opening the issue? THIS is really fast!
The architecture is still not ideal but we hacked around it maybe 2 days after i opened this issue.

**Comment by ecoologic** [comment]
I'm impressed you remember your solution! The lib went un-maintained and we picked it back up again a month ago. We're closing old issues.

We'll try to be a bit faster moving forward.

Thank you.
