### ISSUE TITLE
How to retrieve average ticket metrics?

### ISSUE THREAD

**Issue by sdrenth** [zendesk/zendesk_api_client_php#362]
Is it possible to retrieve average ticket metrics for all tickets at once via a single API call or do I need to retrieve all ticket metrics one by one and calculate the average metrics myself?

**Comment by ecoologic** [comment]
Hi,

 thank you for your request,
are you still interested in a solution for this issue?

**Comment by sdrenth** [comment]
Hi @ecoologic,

For me it's no longer required, I've moved on with my life 😄

**Comment by ecoologic** [comment]
Glad this didn't block you. We'll try to be a bit more responsive moving forward.

Thank you!
