### ISSUE TITLE
Rename findTwicket() to findTwitterTicketStatus()

### ISSUE THREAD

**Issue by OAFCROB** [zendesk/zendesk_api_client_php#367]
Should [findTwicket()|https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Resources/Core/Tickets.php#L116] be rename to be a bit more descriptive to something like findTwitterTicketStatus() as it's not obvious to what it's doing. Or put in an `@see https://developer.zendesk.com/rest_api/docs/core/twitter_channel#getting-twicket-status`.

At a glance it looks like there is a spelling mistake for this and it should be `findTicket` but after reading the comments I understood what it was doing. However, when comparing that to the Zendesk API documentation this is getting the [statuses|https://developer.zendesk.com/rest_api/docs/core/twitter_channel#getting-twicket-status.] 

I also couldn't find an test coverage for this method. I would be happy to look into making the change, but wanted to see if this is something that would be of interest.

**Comment by joseconsador** [comment]
Hi @OAFCROB ,
That is correct, looks like this method was not updated when we switched to v2. Of course, pull requests are always welcome

**Comment by OAFCROB** [comment]
@joseconsador sorry I totally missed this, put in a [PR for the change.](https://github.com/zendesk/zendesk_api_client_php/pull/403)

**Comment by jmramos02** [comment]
Hello! the `findTwicket` was intended. these are tickets that originated from twitter

Thanks!
