### ISSUE TITLE
Expose finding user by external id

### ISSUE THREAD

**Issue by MatTheCat** [zendesk/zendesk_api_client_php#369]
As per https://support.zendesk.com/hc/en-us/community/posts/203453096/comments/204316176 it seems (and would make sense) the API supports finding a user by its external id but I don't see how to make such a query with the SDK.

For now I'm using `findMany` but I would like to use `find` as I only want one user.

**Comment by ecoologic** [comment]
Hi,

 thank you for your request,
are you still interested in a solution for this issue?

**Comment by MatTheCat** [comment]
Hello, this was six years ago so I eventually moved on :sweat_smile:

**Comment by ecoologic** [comment]
The lib went un-maintained and we picked it back up again a few months ago. We're closing old issues.

We'll try to be a bit faster moving forward. Glad you're not still stuck there.

Thank you.
