### ISSUE TITLE
Unit tests written for specific zendesk instance.

### ISSUE THREAD

**Issue by ocke** [zendesk/zendesk_api_client_php#38]
Hey @maximeprades (and @zendesk/quokka),

I would like to chip into this project as well, but a lot of the unit tests are written in such a way it needs access to a specific (I'm guessing sandedboxy) zendesk instance.

For example this one: [ForumsTest.php](../blob/master/tests/Zendesk/API/Tests/ForumsTest.php#L56)

It points to ```$forum = $this->client->forum(22480662)->find(); // don't delete forum #22480662```

While you can instead of relying on an existing ticket, move this testFind() function to below the createTest() and use the outcome of that to test the testFind().

You guys have done this for _some_ tests. For example: [TargetsTest.php](../blob/master/tests/Zendesk/API/Tests/TargetsTest.php#L76).

Is there a specific reason you guys have written the test like this or can I go ahead, rewrite some of the tests, so that *all* test will work with any zendesk instance and doesn't rely on certain tickets or forums to exists?

If you guys give me a heads up I will add that functionality and do a PR.

**Comment by ggrossman** [comment]
Hi,

We've changed the test suite to remove all of the hardcoded ID references.

The test suite should now run cleanly on any Zendesk instance. We also have changed the code to support passing in Zendesk credentials via environment variables when invoking phpunit.

Ideally, we would have unit tests and not just live tests, but we don't have the resources to rewrite the whole test suite at this time.

**Comment by ocke** [comment]
I saw that. @shanitang did a great job :+1:
