### ISSUE TITLE
Can't find tickets by external_id

### ISSUE THREAD

**Issue by deguif** [zendesk/zendesk_api_client_php#385]
I'm currently using the zendesk api client to find tickets with a specific external id.
In my case, when making the query with the client, I got a 400 bad request.

Here the's code: `$this->client->tickets()->findMany(['74'], [], 'external_ids')`

Which leads to this error: `Client error: GET https://xxxx.zendesk.com/api/v2/tickets/show_many.json?external_ids=74 resulted in a 400 Bad Request`

For users it works fine but the call is slightly different: `$this->client->users()->findMany(['external_ids' => ['74']])`

Is there something I'm doing wrong?

**Comment by Boggimedes** [comment]
Same issue.

**Comment by joseconsador** [comment]
Hi @deguif 

The way to do it would be `$this->client->tickets()->findAll(['external_ids' => ['74']])`.
Let me know if that helps.

Joms
