### ISSUE TITLE
Ticket Date and Multiple Comments

### ISSUE THREAD

**Issue by iamshehryar** [zendesk/zendesk_api_client_php#394]
Hey,

I am having issues with Created_at and Multiple comments. Can you please let me know how can I pass Created_at and multiple comments?

I am using this : 

`$newTicket = $client->tickets()->create([
            'subject'  => $title,
            'created_at' => '2010-06-25T10:15:18Z',
            'updated_at' => '2010-06-25T10:15:18Z',
            'comment'  => array(
                'html_body' =>'Hello',
                'created_at' => '2010-06-25T10:15:18Z',
                'updated_at' => '2010-06-25T10:15:18Z'
            )
        ]);`

Thanks,

**Comment by joseconsador** [comment]
@iamshehryar It is not possible to set the `created_at` as that is a *Read-only* property.
