### ISSUE TITLE
How to get reason why ticket creation fails?

### ISSUE THREAD

**Issue by mtymek** [zendesk/zendesk_api_client_php#40]
When trying to create tickets via API, I sometimes get following error:

    Response to Zendesk\\API\\Tickets::create is not valid. Call $client->getDebug() for details

However, all I can get from getDebug() is HTTP code:

    HTTP/1.1 422 Unprocessable Entity

Looking briefly at the source code, it is not possible to extract exact reason why entity is not valid. Or am I missing something?

**Comment by buheryfi** [comment]
@fhferreira @mtymek are you both still having intermittent issues when using the same code?
