### ISSUE TITLE
Getting SLAs while filtering on status

### ISSUE THREAD

**Issue by Splendoid** [zendesk/zendesk_api_client_php#438]
So the company i work for has a Zendesk account with 3000+ tickets. A lot of them are closed and only a few are open; like 200.
They want a system where they can see how many tickets are open, In what catagory a ticket is and most important; if a new, open, pending or hold ticket has an SLA.
I tried using   `sideload(['metric_events','slas'])->findAll(['status' => "open", 'per_page' => 100, 'page' => 4])`    and that way i do get SLA's but because there are so many closed tickets, the site takes an eternity to load and even then it only loads 100. I know that's because of the pages but almost every page is filled with closed tickets.
The second thing i tried was   `sideload(['metric_events','slas'])->find('type:ticket status<closed')`  . This time the site loaded much faster and i didn't get any closed tickets, GREAT, but I wasn't able to see the SLA's.

So my question is: Is it even possible to filter on status and see if the ticket has an SLA? If yes, how is it done and if no, how would you try to solve this?

**Comment by ecoologic** [comment]
Hi,

 thank you for your request,
are you still interested in a solution for this issue?

**Comment by Splendoid** [comment]
No thank you, I no longer work for that company and I completely forgot I even opened an issue here.
