### ISSUE TITLE
tickets()->findall() only returning first 100 tickets?

### ISSUE THREAD

**Issue by itshaydendev** [zendesk/zendesk_api_client_php#447]
I'm sure this is a PEBCAK error, but for some reason `tickets()->findAll()` is only giving back the first hundred tickets.

```php
	$zendesk = new Zendesk();
	$tickets = $zendesk->tickets()->findAll();
```

Not sure what I'm doing wrong. Is there a default limit of 100 per request?

**Comment by rodjsta** [comment]
https://developer.zendesk.com/rest_api/docs/support/tickets

![image](https://user-images.githubusercontent.com/32949856/78891711-69212e80-7aab-11ea-9699-7ac1790b80d0.png)

**Comment by itshaydendev** [comment]
Ah, thanks, wasn't aware of that. :)
