### ISSUE TITLE
Consider updating the Guzzle version to ^6.0|^7.0

### ISSUE THREAD

**Issue by leonardfischer** [zendesk/zendesk_api_client_php#454]
Hello,

would it be okay to update the version of `guzzlehttp/guzzle` from `^6.0` to `^6.0|^7.0`? I believe there should be no major BC breaking changes for you.

Best regards,
Leo

**Comment by aglipanci** [comment]
This is really important because if the package is used with a PHP framework like Laravel it will prevent future updates.

**Comment by drdrak3** [comment]
This is holding me back from upgrading one of my systems to Laravel 8

**Comment by derekps** [comment]
See https://github.com/zendesk/zendesk_api_client_php/pull/453

**Comment by gkatechis** [comment]
This has been bumped in the latest version, 2.2.10. Please note that this is still technically an unmaintained repo, so no guarantee that we will be able to similar things in the future!

**Comment by leonardfischer** [comment]
Now we'd just need to update the packagist package https://packagist.org/packages/zendesk/zendesk_api_client_php ;)

**Comment by gkatechis** [comment]
> Now we'd just need to update the packagist package https://packagist.org/packages/zendesk/zendesk_api_client_php ;)

Woof, that one is out of my realm, but I'll check to see if anyone knows how we pushed updates there!

**Comment by leonardfischer** [comment]
Hey @gkatechis that looks very good, works for me :) Thanks a lot!
