### ISSUE TITLE
\Zendesk\API\Resources\Core\Search::find has wrong parameter type annotation

### ISSUE THREAD

**Issue by georgms** [zendesk/zendesk_api_client_php#462]
[\Zendesk\API\Resources\Core\Search::find](https://github.com/zendesk/zendesk_api_client_php/blob/13f0c1f299796cc271a2b84c7eda98b3ab0c97a9/src/Zendesk/API/Resources/Core/Search.php#L39) parameter `$query` has the type annotation `null` while it should clearly be `string`:

https://github.com/zendesk/zendesk_api_client_php/blob/13f0c1f299796cc271a2b84c7eda98b3ab0c97a9/src/Zendesk/API/Resources/Core/Search.php#L32

I came across this while validating a project with PHPStan.

**Comment by pointybeard** [comment]
Hit this one also while running PHPStan also. Quick fix is to add a line like this to `phpstan.neon.dist` in the `ignoreErrors` segment:

```yaml
  ignoreErrors:
    - '#Parameter \#1 \$query of method Zendesk\\API\\Resources\\Core\\Search::find\(\) expects null, string given.#'
```

Proper fix, of course, is to change `* @param null  $query ` to `* @param string $query ` as mentioned.

**Comment by pointybeard** [comment]
Just popped through PR #486 for this one.
