### ISSUE TITLE
PHP8 Error: array_merge() does not accept unknown named parameters

### ISSUE THREAD

**Issue by roberttolton** [zendesk/zendesk_api_client_php#473]
Line in reference:
https://github.com/zendesk/zendesk_api_client_php/blob/b451b743d9d6d81a9abf7cb86e70ec9c5332123e/src/Zendesk/API/HttpClient.php#L441

Should be changed to:
```
return call_user_func_array('array_merge', array_values($sideloads));
```

**Comment by ecoologic** [comment]
Thank you for your contribution. This has been done:

https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/HttpClient.php#L446
