### ISSUE TITLE
php 5.6 Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/clients/client1/web6/web/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 47

### ISSUE THREAD

**Issue by HolgerGERMANY** [zendesk/zendesk_api_client_php#474]
Hi,
I have simple code to retrieve tickets. I get these error. Any help?
Thx.

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/clients/client1/web6/web/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 47

php 5.6
thx.

**Comment by ecoologic** [comment]
I f you can use the recent master branch this problem should be solved. Otherwise, you can wait and we'll cut a new release.
