### ISSUE TITLE
Update Packagist with the new version

### ISSUE THREAD

**Issue by aglipanci** [zendesk/zendesk_api_client_php#479]
The newly released version [v2.2.12](https://github.com/zendesk/zendesk_api_client_php/releases/tag/v2.2.12) is not pushed on Packagist and it's not available for installation through Composer.

Can you please update it?

**Comment by Lydnasty** [comment]
+1

**Comment by BafS** [comment]
@yoshdog would it be possible to update your package on packagist?
https://packagist.org/packages/zendesk/zendesk_api_client_php

**Comment by vanessametageek** [comment]
It is on packagist now!
