### ISSUE TITLE
Unmerged PRs

### ISSUE THREAD

**Issue by gjuric** [zendesk/zendesk_api_client_php#487]
Dear maintainers, can we get some support from you to test/merge https://github.com/zendesk/zendesk_api_client_php/pull/480 and push a new version out to packagist?

**Comment by jasonlav** [comment]
+1

**Comment by billriess** [comment]
Is this project no longer maintained?

**Comment by gjuric** [comment]
I will close this issue since the PR was eventually merged after a long wait.

It will probably be hard to get a proper response to your question from maintainers since they are not keen on communicating with the community.
