### ISSUE TITLE
FindAll method Ambiguity in Error Webhooks

### ISSUE THREAD

**Issue by nabeel-sajid-qbatch** [zendesk/zendesk_api_client_php#497]
An alias was defined for method findAll(), which exists in both Zendesk\API\Traits\Resource\Defaults
and Zendesk\API\Traits\Resource\FindAll. Use Zendesk\API\Traits\Resource\Defaults::findAll or
Zendesk\API\Traits\Resource\FindAll::findAll to resolve the ambiguity in

**Comment by joshlopes** [comment]
We are experiencing this same issue. On 2.2.13 this file doesn't exist. A feature was added on these last two patches and they are broken and make php/vendor/phpstan fail. Needs to be addressed.

**Comment by oradwell** [comment]
looks like it was broken in #482 . @7ail what do you think?

**Comment by KayKursawe** [comment]
Still an issue. I can't fall back to 2.2.13, since I'm using guzzlehttp/psr7: ^2.0.
Any plans on fixing this shortly?
