### ISSUE TITLE
Users->findAll() bug found

### ISSUE THREAD

**Issue by ThomasCroonen** [zendesk/zendesk_api_client_php#50]
Finding users with the roles "admin" and "agent" was resulting in a not working link.
zendesk.com/users.json&role[]=agent&role[]=admin

As we can see the link should be : 
zendesk.com/users.json?role[]=agent&role[]=admin

Solution:
<b>File:</b> src\Zendesk\API\Users.php
<b>Online:</b> 43
<b>&</b>role[]='.implode('&role[]=', $params['role']) 
Should be 
<b>?</b>role[]='.implode('&role[]=', $params['role'])

**Comment by atroche** [comment]
looks like this is fixed now.

**Comment by txxxc** [comment]
Hey, 

How do I query two roles (role[]=agent&role[]=admin) in V2?
