### ISSUE TITLE
Repository maintenance status

### ISSUE THREAD

**Issue by gtjamesa** [zendesk/zendesk_api_client_php#514]
Hi there,

I can see in the README that this repo has been marked as unsupported, but it is still receiving commits. Could you please let me know the current status of this repository? Has the unsupported tag been dropped?

**Comment by comxd** [comment]
Definitively not a good new from Zendesk, I am also interested to know why this project is abandoned, or is it deprecated in favor of another (PHP) client?

**Comment by gtjamesa** [comment]
@ecoologic

**Comment by jabeler** [comment]
Related
https://github.com/zendesk/zendesk_api_client_php/pull/507

**Comment by simonmaass** [comment]
@7ail could you please explain why this is deprecated?

**Comment by ecoologic** [comment]
The issue of the state of the library is being discussed internally, but there is no resolution yet.

**Comment by comxd** [comment]
Hello @ecoologic ,

Any news about on this?

**Comment by snatchblock** [comment]
Hi everyone,

Thank you for your patience, and my sincere apologies for the delayed response.

I am the Product Manager for APIs at Zendesk and collaborate closely with @ecoologic. I will provide clarity on the current status of the repository.

TL;DR - We've made major updates to the repository, particularly to support the Cursor Based Pagination (CBP) Model. However, continuous maintenance is not planned. The library was disbanded when the original team moved to other responsibilities, and efforts to find resources for maintenance faced challenges in matching language (PHP) skills.

Long:

The library underwent significant changes, primarily geared towards supporting the Cursor Based Pagination (CBP) Model. This improvement initiative was crucial to ensure that developers using the library wouldn't miss out on the advantages of CBP. Collaborating with @ecoologic, we not only addressed CBP but also merged some more related and simpler PRs during this update.

Unfortunately, the original team responsible for the library transitioned to other roles, resulting in the disbandment of the project and a loss of ownership. Despite my best attempts to find resources for ongoing maintenance, I encountered hurdles in aligning language skills with the specific needs of the library and the long term commitment in allocation of the resources.

While continuous maintenance is not currently scheduled, I am actively working on securing additional capacity to provide support when major changes are needed. Commitment to continuous maintenance remains under consideration and will depend on future developments.

I appreciate your understanding and patience as we move forward. If you have any further questions or concerns, feel free to reach out.

**Comment by snatchblock** [comment]
I am also willing to make the repo open by adding interested external maintainers the right to merge the PRs.

**Comment by alxndr-w** [comment]
So you are hiring to fill the gap. Right?

**Comment by snatchblock** [comment]
Yes. 

I was informed by Engineering that a business case will be made for the resource gap. It won't be specifically for PHP, but a position for library management and other functions.

**Comment by cryptomail** [comment]
We're pleased to announce that we will be continuing support for Zendesk API Client for PHP.
This is the result of your comments, but most of all, the result of our (Zendesk's) commitment to the larger community.
We recognize that a number of customers and integrators employ this library and as such, we feel it's in our best interest to continue support.

Level-setting expectations: 
Maintenance will be performed on an on-going basis at a reasonable cadence.
Major security and vulnerability issues will be prioritized over lesser features.
We welcome community engagement and feedback to continuously improve the library.
