### ISSUE TITLE
Future expantion to Helpcenter API

### ISSUE THREAD

**Issue by dragem** [zendesk/zendesk_api_client_php#54]
Hi, is there any planning for a expantion with the helpcenter api (And maybe Zopim)?

**Comment by HarryLyu** [comment]
Hello! I'm also interesting in implementing Help Center API into PHP client. Any plans to do it?

**Comment by ggrossman** [comment]
Hi @dragem, @HarryLyu,

Thanks for your interest! We don't have any short-term plans to develop HC or Zopim support. If you are interested in contributing some code here, we'd be delighted.

**Comment by HarryLyu** [comment]
@ggrossman, thanks for your answer. We'll try to make a pull request in few weeks :)

**Comment by bviolier** [comment]
@HarryLyu Did you ever get around it? We are looking into it also :-)

**Comment by HarryLyu** [comment]
@bviolier unfortunately – no, we didn't started this task and currently have no plans about it :(
