### ISSUE TITLE
3.1.0 not published on packagist

### ISSUE THREAD

**Issue by MrJuliuss** [zendesk/zendesk_api_client_php#540]
Hi, Version 3.1.0 is not bublished on packagist, auto publish seems to be broken.

**Comment by token-cjg** [comment]
Hi @MrJuliuss, thanks for pointing this out. https://packagist.org/packages/zendesk/zendesk_api_client_php#v3.1.0 should be available now for use.

**Comment by MrJuliuss** [comment]
Hi, Thanks !
