### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by veshant** [zendesk/zendesk_api_client_php#541]
Failed to query zendesk with message: Creation of dynamic property Zendesk\API\Resources\Core\Users::$endpoint is deprecated

**Comment by jookyg** [comment]
+1 on this. My org just upgraded PHP and started getting the deprecation warning. We use the library in a custom Drupal webform handler, and the warning is breaking the AJAX in the Drupal webforms config UI. I'll need to suppress it until a fix is released.

**Comment by token-cjg** [comment]
Thanks for raising this issue @veshant, and moreover thank you for submitting a fix with https://github.com/zendesk/zendesk_api_client_php/pull/542 🏆 

Your contribution has been accepted and released with version 3.1.1.

**Comment by veshant** [comment]
Thanks for merging.
