### ISSUE TITLE
Is Incremental Ticket API supported?

### ISSUE THREAD

**Issue by shehi** [zendesk/zendesk_api_client_php#58]
Title says it all: is Incremental Ticket API supported by this library? I checked the code thoroughly and couldn't find any sign of it in there. Thanks!

@see https://developer.zendesk.com/rest_api/docs/core/ticket_export

**Comment by davidstanley01** [comment]
That link above is going to a 404 page, now.  Is the endpoint still good? Or should we be hitting the `incremental/tickets.json` endpoint and the feature in #80  instead?
