### ISSUE TITLE
API's grandiose exception handling problem!

### ISSUE THREAD

**Issue by shehi** [zendesk/zendesk_api_client_php#59]
Please revamp whole exception handling of the API so that every status code for exception cases are reflected correctly. E.g. instead of having one ```ResponseException``` let's have separate exceptions such as ```TooManyConnectionsException```, ```MissingParameterException``` etc (and of course have unit-test-case for each exception handled). For every single status code at least. In it's current case, there is no way of managing the flow of code-logic, based upon the result's status code. E.g., it would be awesome to know before hand if one receives ```TooManyConnectionsException``` and upon the exception wait for necessary ```Retry-time``` seconds and try again.

With all due respect, this code needs very good peer-reviewing! It looks as if it was written for the sake of being written!

**Comment by ocke** [comment]
I couldn't agree more! 'Error' is not very helpful, and we ended up putting var_dump to see what the hell is going on.

**Comment by atroche** [comment]
Yeah, you guys are 100% right! We're looking at doing a pretty big rewrite at the moment, and one of our chief goals for that will be sane error handling. I'm going to close this issue out now, but trust me when I say that it's gonna get solved =)
