### ISSUE TITLE
Make release tag

### ISSUE THREAD

**Issue by back-2-95** [zendesk/zendesk_api_client_php#6]
Hello,

You could make some version as release?
This way when using with composer, you could use version instead of "dev-master" and that way prevent "unbound version constraints (dev-master) should be avoided" warning with composer.

Thanks!

**Comment by upchuk** [comment]
+1 Agree!

**Comment by lyrixx** [comment]
I think this repository is not maintained anymore. Does someone want to fork and maintain it?

**Comment by chrisminett** [comment]
I had a PR merged a month ago, so I don't think that's entirely true. Unfortunately this repo doesn't appear to be properly linked to Packagist, as that's still showing a build from October 2014 for dev-master.

**Comment by ggrossman** [comment]
Hi folks. I'm the engineering lead for the API team at Zendesk.

This library has slipped through the cracks at Zendesk for some time but we're now taking proper ownership of it.

We've had an engineer and get the test suite working and running under Travis-CI, and we've merged most of the PR's submitted by developers in the community. We're just working through the last ones now.

Now that we've got a green build, we've tagged the current state of the code v1.0.0.

This library was developed externally and we're mostly Ruby developers without a lot of PHP experience. Recommendations are welcome. For instance, we're not really familiar with Packagist; if there's any guidance you can offer there, @chrisminett , let us know.

**Comment by back-2-95** [comment]
Thank you. Looking for the v1.0.0

**Comment by chrisminett** [comment]
@ggrossman Great news!

As for Packagist, it requires adding the Packagist service in the GitHub repository settings. There's more info on Packagist [here](https://packagist.org/profile/) (when logged in).

**Comment by mikealmond** [comment]
Any update on tagging a release? It looks like the tests are passing.

**Comment by atroche** [comment]
Looks like releases are working as expected.
