### ISSUE TITLE
open_basedir & CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by danalexander** [zendesk/zendesk_api_client_php#64]
If open_basedir is set, PHP issues a warning,
```
PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in [...]/zendesk_api_client_php/src/Zendesk/API/Http.php on line 110
```

**Comment by buheryfi** [comment]
@danalexander, where are you setting open_basedir? In the php.ini or in another location?  Can you also give a sample of what you are setting it to in relation to your client library so we can understand the environment you're using?
