### ISSUE TITLE
how to extract only open tickets from Zendesk?

### ISSUE THREAD

**Issue by rishwari** [zendesk/zendesk_api_client_php#71]

**Comment by buheryfi** [comment]
@rishwari can you provide the code that you've tried using and what results you're getting?

**Comment by atroche** [comment]
@rishwari I'm going to close this, but feel free to get back in touch if you still need help.

**Comment by netbrothers-tr** [comment]
You could use the following snippet if you look for a specific ticket requester for instance:

```
$query = 'type:ticket status:open requester_id:' . $requesterId;
$ticketsFound = $zendeskClient->search()->find($query);
```
Use the [search API](https://developer.zendesk.com/rest_api/docs/core/search) to build the query you need.
