### ISSUE TITLE
zendesk_api_client_php

### ISSUE THREAD

**Issue by nithishj** [zendesk/zendesk_api_client_php#79]
Hi,

 After i Load my library directly by downloading from git repositoy. 
I get the error as:

Fatal error: Class 'Zendesk\API\Debug' not found in C:\xampp\htdocs\Former\zendesk_api_client\src\Zendesk\API\Client.php on line 240

**Comment by nithishj** [comment]
I included debug.php and more classes.

then suddenly i got:
Fatal error: Class 'Zendesk\API\ClientAbstract' not found in C:\xampp\htdocs\Former\zendesk_api_client\src\Zendesk\API\Tickets.php on line 13

I went to 'Tickets.php' and included 'ClientAbstract.php'

then i got

Fatal error: Cannot redeclare class Zendesk\API\ClientAbstract in C:\xampp\htdocs\Former\zendesk_api_client\src\Zendesk\API\ClientAbstract.php on line 10

How do include all the libraries into my script apart from using composer?

**Comment by ocke** [comment]
You have to use composer. You're missing this code:

```
include("vendor/autoload.php");
use Zendesk\API\Client as ZendeskAPI;
```

But that only works after you installed it with composer...
