### ISSUE TITLE
Add support to make calls via a proxy server

### ISSUE THREAD

**Issue by micahwalter** [zendesk/zendesk_api_client_php#83]
I'd like to be able to use this from behind a proxy server. Can we add something like 

    $curl->setopt(CURLOPT_PROXY, $proxy);

to the Http.php file along with a setProxy function in the Client?

-micah

**Comment by atroche** [comment]
@micahwalter thanks for the suggestion! can you help us by showing us examples of how other prominent PHP API clients have handled proxy settings?

**Comment by micahwalter** [comment]
Sure
I would have a look at Twilio's PHP SDK or Mandrill's.

They're both using curl, and just have an option in the constructor to set a proxy host and port, which tells curl to set the correct options.

Micah

**Comment by micahwalter** [comment]
To be more clear, on the Mandrill PHP SDK, I added the following to https://bitbucket.org/mailchimp/mandrill-api-php/src/9f336b08ea148c80db3b694f3dc737cd4f414e19/src/Mandrill.php?at=master

around line 92

.. I haven't submitted a pull request for it yet, but thats about all I had to do...

    public function useProxy($proxy){
		curl_setopt($this->ch, CURLOPT_PROXY, ''.$proxy);
		
		return $this;
	}

**Comment by jwswj** [comment]
@micahwalter we're now using the Guzzle HTTP Client in v2, so you could leverage http://guzzle.readthedocs.org/en/latest/request-options.html#proxy
We're not planning to add this at the moment, but would welcome a pull request.
