### ISSUE TITLE
Open call for feedback

### ISSUE THREAD

**Issue by atroche** [zendesk/zendesk_api_client_php#89]
Hey guys, I've cc'd everyone who's contributed to this repo recently.

@miogalang, @joseconsador and I are about to start a week-long intensive on this project in the Manila office. What do you think we should work on? I've identified a few things so far:

-    [Better exception handling](https://github.com/zendesk/zendesk_api_client_php/issues/59) (thanks @shehi and @ocke)
-    [Better unit test coverage](https://github.com/zendesk/zendesk_api_client_php/issues/38#issuecomment-70059972) (thanks @ggrossman)
-    Full support for all endpoints in the core API
-    Higher code quality in general (using static analysis, if possible)
-    A consistent interface for resources (i.e. the constructors, getters, setters, etc. should all work the same whether you're working with apps, tickets or anything else)
-    More information in the README about what the library can do, and how to use it

Anything else you'd like to mention? Now's a good time =)

@mtibben @jurajseffer @andreionut @bvarent @ha-quidco @miogalang @jwswj @mmolina

**Comment by atroche** [comment]
cc @dpawluk @kssmith @buheryfi @shanitang @davesidious @lookbadgers @chrisminett @bbrink68 @gonzunigad

**Comment by patrickconroy** [comment]
It's really confusing that this API doesn't interact with the help_center API at all. For instance, 

https://support.rockstargames.com/api/v2/help_center/categories/200013096.json
https://support.rockstargames.com/api/v2/categories/20107766.json

Will the v2 (branch) be able to interact with the help center as well as the core? Or should there be namespaces for `Core` and `HelpCenter` ? Otherwise I don't know how you'd reconcile the fact that `Categories` is valid in both.

**Comment by atroche** [comment]
Personally I think we should get v2 launched, and get the repo to a higher level of code quality + test coverage before we start adding in major new features. Especially seeing as the other Zendesk API clients don't support it yet.

**Comment by shehi** [comment]
Agreed with @atroche : It'd be better to solve standing problems and then adding new features.

**Comment by jwswj** [comment]
We're focusing on the initial core APIs first, but will provide a framework for Help Center, Voice & other endpoints through namespacing.

**Comment by jwswj** [comment]
We've been making some great progress on the new version over the past week. Check out https://github.com/zendesk/zendesk_api_client_php/pull/99 if you're interested.
